AWSTemplateFormatVersion: 2010-09-09
Description: This file created instance with vpc and sg

Resources:
  # vpc creation
  DemoVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: "false"
      EnableDnsSupport: "false"

      Tags:
        - Key: Name
          Value: DemoVpc

  # public subnet creation
  DemoPubsubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-south-1a # Region
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: "true" # access to internet
      Tags:
        - Key: Name
          Value: DemoPubsubnet
      VpcId: !Ref DemoVpc

  # private subnet creation
  DemoPrisubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-south-1a # Region
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: "false" # no public access
      Tags:
        - Key: Name
          Value: DemoPrisubnet
      VpcId: !Ref DemoVpc

  # internet gateway creation
  DemoIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: DemoIgw

  # attach igw to vpc
  DemoIgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref DemoIgw
      VpcId: !Ref DemoVpc

  # security group creation
  DemoSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http access to instance
      GroupName: DemoSg
      SecurityGroupIngress:
        - CidrIp: 10.0.1.0/24
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
      Tags:
        - Key: Name
          Value: DemoSg
      VpcId: !Ref DemoVpc

  # instance creation
  DemoEc2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a # region
      ImageId: ami-0aebec83a182ea7ea # ami id of required server
      InstanceType: t2.nano # Size of instance
      KeyName: mumbai-key
      SubnetId: !Ref DemoPubsubnet
      SecurityGroupIds:
        - !Ref DemoSg
      Tags:
        - Key: Name
          Value: DemoEc2

# display ids of resource created
Outputs:
  InstanceId:
    Description: Instance id of the linux ec2 created
    Value: !Ref DemoEc2

  PublicIp:
    Description: Public ip of the instance created
    Value: !GetAtt DemoEc2.PublicIp

  VPCId:
    Description: VPC id of the vpc attached to linux ec2
    Value: !Ref DemoVpc
